# Dockerfile.profiel
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set working directory
WORKDIR /app

# Copy the project file and restore dependencies
COPY UC1-Profielpagina/Showcase-Profielpagina.csproj ./
RUN dotnet restore

# Copy the rest of the code and build the app
COPY UC1-Profielpagina/. ./
RUN dotnet publish -c Release -o out

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "Showcase-Profielpagina.dll"]

